# - type: latheRecipe
#   id: LPPTelebaton
#   result: LPPTelebaton
#   completetime: 15
#   materials:
#     Plastic: 150

# - type: latheRecipe
#   id: LPPCartridgeIncendiaryM4A1
#   result: LPPCartridgeIncendiaryM4A1
#   category: Ammo
#   completetime: 2
#   materials:
#     Plastic: 20

# - type: latheRecipe
#   id: LPPCartridgeUraniumM4A1
#   result: LPPCartridgeUraniumM4A1
#   category: Ammo
#   completetime: 2
#   materials:
#     Plastic: 20
#     Uranium: 10

# - type: latheRecipe
#   id: LPPCartridgePracticeM4A1
#   result: LPPCartridgePracticeM4A1
#   category: Ammo
#   completetime: 2
#   materials:
#     Steel: 20

# - type: latheRecipe
#   id: LPPCartridgeM4A1Lethal
#   result: LPPCartridgeM4A1Lethal
#   category: Ammo
#   completetime: 2
#   materials:
#     Steel: 20

# - type: latheRecipe
#   id: LPPMagazineRifleM4A1Lethal
#   result: LPPMagazineRifleM4A1Lethal
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 375

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1Lethal
#   result: LPPMagazineBoxM4A1Lethal
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 1150

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1BigPractice
#   result: LPPMagazineBoxM4A1BigPractice
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 1150

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1Incendiary
#   result: LPPMagazineBoxM4A1Incendiary
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 950

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1Practice
#   result: LPPMagazineBoxM4A1Practice
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 900

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1Uranium
#   result: LPPMagazineBoxM4A1Uranium
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 950
#     Uranium: 95

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1Rubber
#   result: LPPMagazineBoxM4A1Rubber
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 950

# - type: latheRecipe
#   id: LPPMagazineBoxM4A1BigLethal
#   result: LPPMagazineBoxM4A1BigLethal
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 1150

# - type: latheRecipe
#   id: LPPC4Low
#   result: LPPC4Low
#   completetime: 10
#   materials:
#     Plastic: 375
#     Plasma: 375

# - type: latheRecipe
#   id: LPPMagazineBoxMinigunPractice
#   result: LPPMagazineBoxRifleMinigunPractice
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 500

# - type: latheRecipe
#   id: LPPMagazineBoxMinigunRubber
#   result: LPPMagazineBoxRifleMinigunRubber
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 350
#     Plastic: 600

# - type: latheRecipe
#   id: LPPMagazineBoxMinigun
#   result: LPPMagazineBoxRifleMinigun
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 750

# - type: latheRecipe
#   id: LPPMagazineMagnumSubMachineGun
#   result: MagazineMagnumSubMachineGun
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 375

# - type: latheRecipe
#   id: LPPMagazineBoxAntiMaterielNL
#   result: LPPMagazineBoxAntiMaterielNonLethal
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 2000

# - type: latheRecipe
#   id: LPPMagazineBoxAntiMaterielCP
#   result: LPPMagazineBoxAntiMaterielCocnterePiercing
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 3000

# - type: latheRecipe
#   id: LPPCartridgeAntiMaterielNL
#   result: LPPCartridgeAntiMaterielNonLethal
#   category: Ammo
#   completetime: 1
#   materials:
#     Plastic: 200

# - type: latheRecipe
#   id: LPPCartridgeAntiMaterielCP
#   result: LPPCartridgeAntiMaterielCP
#   category: Ammo
#   completetime: 1
#   materials:
#     Steel: 300

# - type: latheRecipe
#   id: LPPWeaponGoliathSniper
#   result: LPPWeaponGoliath
#   completetime: 15
#   materials:
#     Plastic: 2000
#     Steel: 10000
#     Glass: 2500

# - type: latheRecipe
#   id: LPPMagazinePistolPF20Lethal
#   result: LPPMagazinePistolPF20lethal
#   category: Ammo
#   completetime: 5
#   materials:
#    Steel: 550

# - type: latheRecipe
#   id: LPPMagazinePistolPF20Practice
#   result: LPPMagazinePistolPF20Practice
#   category: Ammo
#   completetime: 5
#   materials:
#    Steel: 350

# - type: latheRecipe
#   id: LPPMagazinePistolPF20Rubber
#   result: LPPMagazinePistolPF20Rubber
#   category: Ammo
#   completetime: 5
#   materials:
#    Plastic: 400

# - type: latheRecipe
#   id: LPPMagazinePistolPF20Uranium
#   result: LPPMagazinePistolPF20Uranium
#   category: Ammo
#   completetime: 5
#   materials:
#    Plastic: 450
#    Uranium: 75

# - type: latheRecipe
#   id: LPPMagazinePistolPF20Incendiary
#   result: LPPMagazinePistolPF20Incendiary
#   category: Ammo
#   completetime: 5
#   materials:
#    Plastic: 550

# - type: latheRecipe
#   id: LPPMagazineM4A1Practice
#   result: LPPMagazineRifleM4A1Practice
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 300

# - type: latheRecipe
#   id: LPPMagazineM4A1Rubber
#   result: LPPMagazineRifleM4A1Rubber
#   category: Ammo
#   completetime: 5
#   materials:
#     Plastic: 475

# - type: latheRecipe
#   id: LPPMagazineM4A1Uranium
#   result: LPPMagazineRifleM4A1Uranium
#   category: Ammo
#   completetime: 5
#   materials:
#     Steel: 300
#     Uranium: 50
