- type: department
  id: LPPCentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#49C423"
  roles:
  - LPPBlueShieldOfficer
  primary: false
  weight: 101
