name: RSI Validator Secrets

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    paths:
    - '**.rsi/**'

jobs:
  validate_rsis:
    name: Validate RSIs
    if: ${{ vars.SECRETSLINK != '' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Download parts
        run: |
          git clone ${{ secrets.SECRETSMAIN }}
          mv SecretsMain/_PrivateResources/_SPrototypes Resources/Prototypes/
          mv SecretsMain/_PrivateResources/_STextures Resources/Textures/
          mv SecretsMain/_PrivateShared Content.Shared/_PrivateShared
          mv SecretsMain/_PrivateServer Content.Server/_PrivateServer
          mv SecretsMain/_PrivateClient Content.Client/_PrivateClient
      - name: Setup Submodule
        run: git submodule update --init
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Install Python dependencies
        run: |
          pip3 install --ignore-installed --user pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
